### ISSUE TITLE
SBB - wrong file name

### ISSUE THREAD

**Issue by ole1011** [rettichlp/shantybot#42]
**Describe the bug**
The privacy policy file should be named `PRIVACY_POLICY` instead of `PRIVACY_POLICE`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rettichlp** [comment]
Hey @ole1011 
Why should I name my privacy police 'PRICACY_POLICY'? What are the main reasons for this change request? Did you mean 'PRIVACY_POLICY'?

**Comment by ole1011** [comment]
Oops, sorry. My mistake 😂
I meant `PRIVACY_POLICY` 🥙🌮🎾

**Comment by rettichlp** [comment]
Okay, but why should I rename the file?

**Comment by ole1011** [comment]
I honestly think that privacy policy is a better name for that because the title even says policy. It also makes more sense because its not a police station 👮‍♂️🚓🚨
